name: CI/CD Simple Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Enable SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Copy app to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "mkdir -p ~/hello-python-ci"
          scp -o StrictHostKeyChecking=no app.py requirements.txt ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:~/hello-python-ci/ || true

      - name: Install Python and dependencies on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            sudo apt update -y
            sudo apt install -y python3 python3-pip
            if [ -f ~/hello-python-ci/requirements.txt ] && [ -s ~/hello-python-ci/requirements.txt ]; then
              pip3 install -r ~/hello-python-ci/requirements.txt
            fi
          "

      # Remote deployment: like your localhost simulation (nohup + short wait + message)
      - name: Deploy app on VM (remote simulation)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            cd ~/hello-python-ci
            nohup python3 -u app.py > app.log 2>&1 &
            sleep 2
            echo 'App started on remote VM'
            echo '--- app.log ---'
            tail -n +1 app.log || true
          "
