name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: pytest

      # Step 5: Start SSH Agent
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 6: Copy project files to remote server
      - name: Upload app to remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "mkdir -p ~/hello-python-ci"
          scp -o StrictHostKeyChecking=no app.py requirements.txt ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~/hello-python-ci/

      # Step 7: Install Python & dependencies remotely
      - name: Install Python and requirements on remote
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "
            sudo apt-get update -y &&
            sudo apt-get install -y python3 python3-pip &&
            pip3 install -r ~/hello-python-ci/requirements.txt
          "

      # Step 8: Deploy app on remote
      - name: Deploy app (remote server)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "
            cd ~/hello-python-ci &&
            nohup python3 app.py > app.log 2>&1 &
            sleep 2 &&
            cat app.log
          "
