name: CI/CD Simple Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get code from GitHub
        uses: actions/checkout@v4

      - name: Enable SSH connection
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Copy app to the VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "mkdir -p ~/hello-python-ci"
          scp -o StrictHostKeyChecking=no app.py ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:~/hello-python-ci/

      - name: Run app with nohup
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            cd ~/hello-python-ci
            nohup python3 app.py > app.log 2>&1 &
            sleep 1
            grep -q 'Hello, World!' app.log
          "
